name: JavaCI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [9, 11, 17, 21]
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: "zulu"
          cache: "maven"
      - name: Build with Maven
        run: |
          mvn clean test -DskipTests
